from enum import StrEnum


class ReasonCode(StrEnum):
    NO_COUNTERPART = "NO_COUNTERPART"
    STALE_REFERENCE = "STALE_REFERENCE"
    AMOUNT_VARIANCE_EXCEEDS_TOLERANCE = "AMOUNT_VARIANCE_EXCEEDS_TOLERANCE"
    DATE_VARIANCE_EXCEEDS_WINDOW = "DATE_VARIANCE_EXCEEDS_WINDOW"
    IN_TRANSIT_NOT_CLEARED = "IN_TRANSIT_NOT_CLEARED"
    DUPLICATE_CANDIDATE = "DUPLICATE_CANDIDATE"
    CURRENCY_FX_MISMATCH = "CURRENCY_FX_MISMATCH"
